# -*- coding: utf-8 -*-
"""Stats 8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lT_ffClgVsum1BY2vaY6dIal1itgSZyR
"""

# %% 1. Imports
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score, silhouette_samples, adjusted_rand_score

sns.set_style("whitegrid")
RANDOM_STATE = 42
os.makedirs("figures", exist_ok=True)

# %% 2. Load the dataset
# In Google Colab, upload diabetes.csv first (or mount Drive and change the path).
df = pd.read_csv("diabetes.csv")
print("Shape:", df.shape)
print(df.head(), "\n")
print(df.describe().T, "\n")

# %% 3. Select features for unsupervised learning
# 'Outcome' is excluded from model development and kept only for comparison later.
features = ["Pregnancies", "Glucose", "BloodPressure", "SkinThickness",
            "Insulin", "BMI", "DiabetesPedigreeFunction", "Age"]
X = df[features].copy()
y = df["Outcome"].copy()

# %% 4. Handle invalid / missing values
# A value of 0 is physiologically impossible for these columns -> treat as missing.
zero_invalid = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]
X[zero_invalid] = X[zero_invalid].replace(0, np.nan)
print("Missing values after replacing invalid zeros:\n", X.isnull().sum(), "\n")

# Median imputation (robust to the skewed distributions, e.g. Insulin).
X = X.fillna(X.median())
assert X.isnull().sum().sum() == 0

# %% 5. Standardize the features (zero mean, unit variance)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# %% 6. Elbow Method + Silhouette Score for k = 2..10
k_range = range(2, 11)
wcss, sil_scores = [], []
for k in k_range:
    km = KMeans(n_clusters=k, n_init=10, random_state=RANDOM_STATE)
    labels = km.fit_predict(X_scaled)
    wcss.append(km.inertia_)                       # within-cluster sum of squares
    sil_scores.append(silhouette_score(X_scaled, labels))

print("k  |   WCSS    | Silhouette")
for k, w, s in zip(k_range, wcss, sil_scores):
    print(f"{k:<3}| {w:9.2f} | {s:.4f}")

fig, ax = plt.subplots(1, 2, figsize=(13, 4.5))
ax[0].plot(list(k_range), wcss, "o-", color="tab:blue")
ax[0].set(title="Elbow Method", xlabel="Number of clusters (k)", ylabel="WCSS (inertia)")
ax[1].plot(list(k_range), sil_scores, "s-", color="tab:green")
ax[1].set(title="Silhouette Score vs k", xlabel="Number of clusters (k)", ylabel="Silhouette score")
plt.tight_layout()
plt.savefig("figures/01_elbow_silhouette.png", dpi=150)
plt.show()

# %% 7. Choose k
# The elbow curve bends gradually, so it is read together with the silhouette score.
# The k with the highest silhouette score is used (k = 2 here), which also matches
# the two known diabetes categories. Override OPTIMAL_K manually if you prefer.
OPTIMAL_K = int(list(k_range)[int(np.argmax(sil_scores))])
print(f"\nSelected k = {OPTIMAL_K} (highest silhouette score)")

kmeans = KMeans(n_clusters=OPTIMAL_K, n_init=10, random_state=RANDOM_STATE)
clusters = kmeans.fit_predict(X_scaled)
final_sil = silhouette_score(X_scaled, clusters)
print(f"Silhouette score for k={OPTIMAL_K}: {final_sil:.4f}")

# Silhouette plot per observation
sample_sil = silhouette_samples(X_scaled, clusters)
fig, ax = plt.subplots(figsize=(7, 5))
y_lower = 10
for c in range(OPTIMAL_K):
    vals = np.sort(sample_sil[clusters == c])
    y_upper = y_lower + len(vals)
    ax.fill_betweenx(np.arange(y_lower, y_upper), 0, vals, alpha=0.7, label=f"Cluster {c}")
    y_lower = y_upper + 10
ax.axvline(final_sil, color="red", ls="--", label=f"Mean = {final_sil:.3f}")
ax.set(title="Silhouette Plot", xlabel="Silhouette coefficient", ylabel="Observations")
ax.legend()
plt.tight_layout()
plt.savefig("figures/02_silhouette_plot.png", dpi=150)
plt.show()

# %% 8. PCA - dimensionality reduction
pca_full = PCA(random_state=RANDOM_STATE).fit(X_scaled)
explained = pca_full.explained_variance_ratio_
cum_explained = np.cumsum(explained)
print("\nExplained variance ratio per component:")
for i, (e, c) in enumerate(zip(explained, cum_explained), 1):
    print(f"  PC{i}: {e:.4f}  (cumulative {c:.4f})")

fig, ax = plt.subplots(figsize=(7, 4.5))
ax.bar(range(1, len(explained) + 1), explained, alpha=0.7, label="Individual")
ax.step(range(1, len(explained) + 1), cum_explained, where="mid", color="red", label="Cumulative")
ax.set(title="PCA Explained Variance", xlabel="Principal component", ylabel="Variance ratio")
ax.legend()
plt.tight_layout()
plt.savefig("figures/03_pca_variance.png", dpi=150)
plt.show()

pca = PCA(n_components=2, random_state=RANDOM_STATE)
X_pca = pca.fit_transform(X_scaled)
print(f"\nVariance captured by PC1 + PC2: {pca.explained_variance_ratio_.sum():.2%}")

loadings = pd.DataFrame(pca.components_.T, index=features, columns=["PC1", "PC2"])
print("\nPCA loadings:\n", loadings.round(3))

plt.figure(figsize=(7, 5))
sns.heatmap(loadings, annot=True, cmap="coolwarm", center=0, fmt=".2f")
plt.title("PCA Loadings")
plt.tight_layout()
plt.savefig("figures/04_pca_loadings.png", dpi=150)
plt.show()

# %% 9. Visualize in 2-D: K-Means clusters vs. actual diabetes outcome
pca_df = pd.DataFrame({"PC1": X_pca[:, 0], "PC2": X_pca[:, 1],
                       "Cluster": clusters, "Outcome": y.values})

fig, ax = plt.subplots(1, 2, figsize=(14, 5.5))
sns.scatterplot(data=pca_df, x="PC1", y="PC2", hue="Cluster", palette="Set1",
                alpha=0.75, s=40, ax=ax[0])
centers_pca = pca.transform(kmeans.cluster_centers_)
ax[0].scatter(centers_pca[:, 0], centers_pca[:, 1], c="black", marker="X", s=220,
              edgecolor="white", label="Centroids")
ax[0].set_title(f"K-Means Clusters (k={OPTIMAL_K}) in PCA Space")
ax[0].legend()

sns.scatterplot(data=pca_df, x="PC1", y="PC2", hue="Outcome",
                palette={0: "tab:blue", 1: "tab:red"}, alpha=0.75, s=40, ax=ax[1])
ax[1].set_title("Actual Diabetes Outcome in PCA Space")
plt.tight_layout()
plt.savefig("figures/05_pca_clusters_vs_outcome.png", dpi=150)
plt.show()

# %% 10. Analyze and interpret the clusters
profile = X.copy()
profile["Cluster"] = clusters
cluster_profile = profile.groupby("Cluster").mean().round(2)
cluster_profile["Size"] = profile.groupby("Cluster").size()
print("\nCluster profiles (mean of original, un-scaled features):\n", cluster_profile.T)

# Heatmap of standardized cluster centres
centers_df = pd.DataFrame(kmeans.cluster_centers_, columns=features,
                          index=[f"Cluster {i}" for i in range(OPTIMAL_K)])
plt.figure(figsize=(10, 3 + OPTIMAL_K * 0.5))
sns.heatmap(centers_df, annot=True, fmt=".2f", cmap="coolwarm", center=0)
plt.title("Cluster Centroids (standardized features)")
plt.tight_layout()
plt.savefig("figures/06_cluster_centroids.png", dpi=150)
plt.show()

# Compare discovered clusters with the known Outcome (used ONLY for evaluation)
ct = pd.crosstab(clusters, y, rownames=["Cluster"], colnames=["Outcome"])
ct_pct = pd.crosstab(clusters, y, rownames=["Cluster"], colnames=["Outcome"],
                     normalize="index").mul(100).round(1)
print("\nCluster vs Outcome (counts):\n", ct)
print("\nCluster vs Outcome (row %):\n", ct_pct)
ari = adjusted_rand_score(y, clusters)
print(f"\nAdjusted Rand Index (clusters vs Outcome): {ari:.4f}")

plt.figure(figsize=(5, 3.5))
sns.heatmap(ct_pct, annot=True, fmt=".1f", cmap="Blues")
plt.title("% of Each Cluster by Diabetes Outcome")
plt.tight_layout()
plt.savefig("figures/07_cluster_vs_outcome.png", dpi=150)
plt.show()

# %% 11. Save results
out = df.copy()
out["Cluster"] = clusters
out["PC1"], out["PC2"] = X_pca[:, 0], X_pca[:, 1]
out.to_csv("diabetes_with_clusters.csv", index=False)
print("\nSaved: diabetes_with_clusters.csv and figures/*.png")

