# -*- coding: utf-8 -*-
"""Stats 9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_xp9eXY7_nTBvybX3ktbKpHmxCDdK7B
"""

pip install shap lime

"""
Model Evaluation, Calibration and Explainable AI
on the Pima Indians Diabetes Dataset
(Random Forest + k-Fold CV + Brier Score + Calibration Curve + SHAP + LIME)

Install (Colab):  !pip install shap lime
Run:              python model_evaluation_explainability.py
The '# %%' markers let the file run cell-by-cell in VS Code / Jupyter / Colab.
"""

# %% 1. Imports
import os
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import shap
from lime.lime_tabular import LimeTabularExplainer

from sklearn.model_selection import (train_test_split, StratifiedKFold,
                                     cross_validate, cross_val_predict)
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.calibration import calibration_curve, CalibratedClassifierCV
from sklearn.metrics import (accuracy_score, f1_score, precision_score, recall_score,
                             roc_auc_score, brier_score_loss, confusion_matrix,
                             ConfusionMatrixDisplay, classification_report)

warnings.filterwarnings("ignore")
RANDOM_STATE = 42
os.makedirs("figures", exist_ok=True)

# %% 2. Load and preprocess the dataset
df = pd.read_csv("diabetes.csv")
print("Shape:", df.shape)
print("Class distribution:\n", df["Outcome"].value_counts(), "\n")

features = [c for c in df.columns if c != "Outcome"]
X = df[features].copy()
y = df["Outcome"].copy()

# Zeros are physiologically impossible for these columns -> treat as missing.
zero_invalid = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]
X[zero_invalid] = X[zero_invalid].replace(0, np.nan)
print("Missing values per column:\n", X.isnull().sum(), "\n")

# %% 3. Train / test split (stratified 80 / 20)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, stratify=y, random_state=RANDOM_STATE)
print(f"Train: {X_train.shape}, Test: {X_test.shape}")

# %% 4. Train a classification model
# Median imputation lives inside the pipeline, so it is learned from training
# data only (no data leakage into validation folds or the test set).
def make_model(**rf_params):
    return Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("rf", RandomForestClassifier(n_estimators=300, min_samples_leaf=3,
                                      random_state=RANDOM_STATE, n_jobs=-1, **rf_params)),
    ])

model = make_model()
model.fit(X_train, y_train)

# %% 5. Stratified k-fold cross-validation (k = 5)
K = 5
cv = StratifiedKFold(n_splits=K, shuffle=True, random_state=RANDOM_STATE)
scoring = ["accuracy", "precision", "recall", "f1", "roc_auc", "neg_brier_score"]
cv_res = cross_validate(make_model(), X_train, y_train, cv=cv, scoring=scoring)

cv_table = pd.DataFrame({m: cv_res[f"test_{m}"] for m in scoring})
cv_table["brier_score"] = -cv_table.pop("neg_brier_score")
cv_table.index = [f"Fold {i}" for i in range(1, K + 1)]
print(f"\n{K}-fold cross-validation results:\n", cv_table.round(4))
summary = pd.DataFrame({"mean": cv_table.mean(), "std": cv_table.std()})
print("\nCV summary (mean ± std):\n", summary.round(4))

fig, ax = plt.subplots(figsize=(8, 4.5))
plot_cols = ["accuracy", "precision", "recall", "f1", "roc_auc"]
ax.bar(plot_cols, cv_table[plot_cols].mean(), yerr=cv_table[plot_cols].std(),
       capsize=5, color="tab:blue", alpha=0.8)
ax.set(title=f"{K}-Fold CV Performance (mean ± std)", ylim=(0, 1), ylabel="Score")
plt.tight_layout()
plt.savefig("figures/01_cv_performance.png", dpi=150)
plt.show()

# %% 6. Bias-variance trade-off: train vs CV accuracy across model complexity
depths = [1, 2, 3, 4, 6, 8, 10, 15, None]
tr_acc, cv_acc = [], []
for d in depths:
    res = cross_validate(make_model(max_depth=d), X_train, y_train, cv=cv,
                         scoring="accuracy", return_train_score=True)
    tr_acc.append(res["train_score"].mean())
    cv_acc.append(res["test_score"].mean())
labels = [str(d) if d else "None" for d in depths]

plt.figure(figsize=(8, 4.5))
plt.plot(labels, tr_acc, "o-", label="Training accuracy")
plt.plot(labels, cv_acc, "s-", label="CV accuracy")
plt.title("Bias-Variance Trade-off (Random Forest max_depth)")
plt.xlabel("max_depth (low = simple / high bias, high = complex / high variance)")
plt.ylabel("Accuracy"); plt.legend(); plt.grid(alpha=0.3)
plt.tight_layout()
plt.savefig("figures/02_bias_variance.png", dpi=150)
plt.show()
print("\nTrain vs CV accuracy by depth:")
for l, a, b in zip(labels, tr_acc, cv_acc):
    print(f"  depth={l:<5} train={a:.4f}  cv={b:.4f}  gap={a-b:.4f}")

# %% 7. Performance on the held-out test set
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

test_metrics = {
    "Accuracy": accuracy_score(y_test, y_pred),
    "Precision": precision_score(y_test, y_pred),
    "Recall": recall_score(y_test, y_pred),
    "F1-score": f1_score(y_test, y_pred),
    "ROC-AUC": roc_auc_score(y_test, y_prob),
}
print("\nTest-set metrics:")
for k, v in test_metrics.items():
    print(f"  {k:<10}: {v:.4f}")
print("\n", classification_report(y_test, y_pred, target_names=["Non-diabetic", "Diabetic"]))

ConfusionMatrixDisplay(confusion_matrix(y_test, y_pred),
                       display_labels=["Non-diabetic", "Diabetic"]).plot(cmap="Blues")
plt.title("Confusion Matrix (Test Set)")
plt.tight_layout()
plt.savefig("figures/03_confusion_matrix.png", dpi=150)
plt.show()

# %% 8. Brier score and calibration curve
brier = brier_score_loss(y_test, y_prob)
baseline_brier = brier_score_loss(y_test, np.full(len(y_test), y_train.mean()))
print(f"\nBrier Score (test)                     : {brier:.4f}")
print(f"Brier Score of a no-skill baseline     : {baseline_brier:.4f}  (always predicts class prior)")

# Compare the raw model with a sigmoid-calibrated version (Platt scaling).
calibrated = CalibratedClassifierCV(make_model(), method="sigmoid", cv=5)
calibrated.fit(X_train, y_train)
y_prob_cal = calibrated.predict_proba(X_test)[:, 1]
brier_cal = brier_score_loss(y_test, y_prob_cal)
print(f"Brier Score (sigmoid-calibrated model) : {brier_cal:.4f}")

# Out-of-fold probabilities on the training set give a less noisy calibration curve.
oof_prob = cross_val_predict(make_model(), X_train, y_train, cv=cv, method="predict_proba")[:, 1]
brier_oof = brier_score_loss(y_train, oof_prob)
print(f"Brier Score (out-of-fold, train)       : {brier_oof:.4f}")

fig, ax = plt.subplots(1, 2, figsize=(13, 5))
for name, yt, yp in [("Random Forest (test)", y_test, y_prob),
                     ("Sigmoid-calibrated (test)", y_test, y_prob_cal),
                     ("Random Forest (out-of-fold, train)", y_train, oof_prob)]:
    frac_pos, mean_pred = calibration_curve(yt, yp, n_bins=8, strategy="quantile")
    ax[0].plot(mean_pred, frac_pos, "o-", label=name)
ax[0].plot([0, 1], [0, 1], "k--", label="Perfectly calibrated")
ax[0].set(title="Calibration Curve", xlabel="Mean predicted probability",
          ylabel="Observed frequency of diabetes")
ax[0].legend(fontsize=8); ax[0].grid(alpha=0.3)

ax[1].hist(y_prob, bins=15, color="tab:blue", alpha=0.8, edgecolor="white")
ax[1].set(title="Distribution of Predicted Probabilities (test)",
          xlabel="Predicted probability of diabetes", ylabel="Count")
plt.tight_layout()
plt.savefig("figures/04_calibration_curve.png", dpi=150)
plt.show()

# %% 9. Prepare imputed data for the explainers
imputer = model.named_steps["imputer"]
rf = model.named_steps["rf"]
X_train_imp = pd.DataFrame(imputer.transform(X_train), columns=features, index=X_train.index)
X_test_imp = pd.DataFrame(imputer.transform(X_test), columns=features, index=X_test.index)

# %% 10. SHAP explanations (TreeExplainer)
explainer = shap.TreeExplainer(rf)
sv = explainer.shap_values(X_test_imp)
# Handle different SHAP versions: keep the values for class 1 (Diabetic).
if isinstance(sv, list):
    shap_vals = sv[1]; base_value = explainer.expected_value[1]
elif np.ndim(sv) == 3:
    shap_vals = sv[:, :, 1]; base_value = explainer.expected_value[1]
else:
    shap_vals = sv; base_value = explainer.expected_value

# Global importance - beeswarm and bar plots
plt.figure()
shap.summary_plot(shap_vals, X_test_imp, show=False)
plt.title("SHAP Summary Plot (impact on P(Diabetic))")
plt.tight_layout()
plt.savefig("figures/05_shap_summary.png", dpi=150, bbox_inches="tight")
plt.show()

plt.figure()
shap.summary_plot(shap_vals, X_test_imp, plot_type="bar", show=False)
plt.title("SHAP Mean |Value| Feature Importance")
plt.tight_layout()
plt.savefig("figures/06_shap_importance_bar.png", dpi=150, bbox_inches="tight")
plt.show()

shap_importance = pd.Series(np.abs(shap_vals).mean(axis=0), index=features).sort_values(ascending=False)
print("\nGlobal feature importance (mean |SHAP|):\n", shap_importance.round(4))

# Local explanations for selected patients:
# one confidently diabetic, one confidently non-diabetic, one uncertain case.
prob_series = pd.Series(y_prob, index=X_test.index)
idx_diabetic = prob_series.idxmax()
idx_healthy = prob_series.idxmin()
idx_uncertain = (prob_series - 0.5).abs().idxmin()
selected = {"Highest risk": idx_diabetic, "Lowest risk": idx_healthy, "Borderline": idx_uncertain}

for label, idx in selected.items():
    pos = X_test.index.get_loc(idx)
    print(f"\n[{label}] patient index {idx}: P(diabetic) = {y_prob[pos]:.3f}, actual = {y_test.loc[idx]}")
    exp = shap.Explanation(values=shap_vals[pos], base_values=base_value,
                           data=X_test_imp.iloc[pos].values, feature_names=features)
    plt.figure()
    shap.plots.waterfall(exp, show=False)
    plt.title(f"SHAP Waterfall - {label} (P={y_prob[pos]:.2f})")
    plt.tight_layout()
    plt.savefig(f"figures/07_shap_waterfall_{label.lower().replace(' ', '_')}.png",
                dpi=150, bbox_inches="tight")
    plt.show()

# %% 11. LIME explanations (local surrogate models)
lime_explainer = LimeTabularExplainer(
    training_data=X_train_imp.values,
    feature_names=features,
    class_names=["Non-diabetic", "Diabetic"],
    mode="classification",
    random_state=RANDOM_STATE,
)

lime_results = {}
for label, idx in selected.items():
    pos = X_test.index.get_loc(idx)
    exp = lime_explainer.explain_instance(
        X_test_imp.iloc[pos].values, rf.predict_proba, num_features=8, num_samples=5000)
    lime_results[label] = exp
    print(f"\nLIME explanation - {label} (patient {idx}):")
    for feat, w in exp.as_list():
        print(f"  {feat:<35} {w:+.4f}")

    fig = exp.as_pyplot_figure()
    plt.title(f"LIME - {label} (P(diabetic)={y_prob[pos]:.2f})")
    plt.tight_layout()
    plt.savefig(f"figures/08_lime_{label.lower().replace(' ', '_')}.png", dpi=150)
    plt.show()

# %% 12. Compare global importance: Random Forest impurity vs SHAP
imp_df = pd.DataFrame({
    "RF impurity importance": pd.Series(rf.feature_importances_, index=features),
    "Mean |SHAP|": shap_importance,
})
imp_df = imp_df / imp_df.sum()            # normalise so both sum to 1
imp_df = imp_df.sort_values("Mean |SHAP|")
imp_df.plot(kind="barh", figsize=(8, 5))
plt.title("Feature Importance: Random Forest vs SHAP (normalised)")
plt.tight_layout()
plt.savefig("figures/09_importance_comparison.png", dpi=150)
plt.show()
print("\nNormalised importance comparison:\n", imp_df.sort_values("Mean |SHAP|", ascending=False).round(4))

# %% 13. Save summary tables
cv_table.round(4).to_csv("cv_results.csv")
shap_importance.rename("mean_abs_shap").to_csv("shap_feature_importance.csv")
print("\nSaved: cv_results.csv, shap_feature_importance.csv and figures/*.png")

